# Site settings
title: "YourTravel Agency"
description: "Discover amazing destinations with us"
url: "https://yourusername.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Destinations
    url: /destinations/
  - title: Packages
    url: /packages/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Contact info
email: info@youragency.com
phone: "+1 234 567 8900"
address: "123 Travel St, City, State"

# Social media
social:
  facebook: youragency
  instagram: youragency
  twitter: youragency