# Site settings
title: "Travel with Kota"
description: "Discover amazing destinations with us"
url: "https://tsheden11.github.io"
baseurl: "/travel-with-kota"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-theme-primer

# Navigation
navigation:
  - title: Home
    url: /
  - title: Destinations
    url: /destinations/
  - title: Packages
    url: /packages/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Contact info
email: info@travelwithkota.com
phone: "+975 123 456 789"
address: "Thimphu, Bhutan"

# Social media
social:
  facebook: travelwithkota
  instagram: travelwithkota